"""Attachment policy service - manage file type whitelist/blacklist."""
import json, os, re, subprocess, uuid
from datetime import datetime

POLICY_FILE = "/etc/cmp/attachment_policy.json"
MIME_CHECKS = "/etc/postfix/mime_header_checks"
BODY_CHECKS = "/etc/postfix/body_checks"
RSPAMD_MIME = "/etc/rspamd/local.d/mime_types.conf"

SYSTEM_BLOCKED_EXT = ["exe","bat","cmd","com","msi","scr","pif","vbs","js","ps1","hta","wsf","wsh","jse","vbe"]
SYSTEM_ALLOWED_EXT = ["pdf","doc","docx","xls","xlsx","ppt","pptx","txt","csv","jpg","jpeg","png","gif","bmp","mp3","mp4","zip","rar"]
SYSTEM_BLOCKED_MIME = ["application/x-msdownload","application/x-sh","text/javascript","application/x-javascript","text/vbscript","application/x-executable"]

def _load():
    if not os.path.exists(POLICY_FILE):
        return []
    with open(POLICY_FILE) as f:
        return json.load(f)

def _save(policies):
    os.makedirs(os.path.dirname(POLICY_FILE), exist_ok=True)
    with open(POLICY_FILE, "w") as f:
        json.dump(policies, f, indent=2, default=str)

def list_policies(tenant_id=None):
    all_p = _load()
    if tenant_id:
        all_p = [p for p in all_p if p.get("tenant_id") == tenant_id or p.get("tenant_id") == "global"]
    return all_p

def create_policy(tenant_id, data):
    policies = _load()
    policy = {
        "id": str(uuid.uuid4())[:8],
        "tenant_id": tenant_id,
        "domain": data.get("domain"),
        "type": data.get("type", "extension"),  # extension|mime|size
        "value": data.get("value", "").lower().lstrip("."),
        "list_type": data.get("list_type", "blacklist"),  # whitelist|blacklist
        "action": data.get("action", "block"),  # block|quarantine|tag|allow
        "description": data.get("description", ""),
        "enabled": True,
        "created_at": datetime.utcnow().isoformat(),
    }
    # Validate not duplicate
    for p in policies:
        if p.get("tenant_id") == tenant_id and p.get("type") == policy["type"] and p.get("value") == policy["value"] and p.get("list_type") == policy["list_type"]:
            return {"error": f"Policy for {policy['value']} already exists"}
    policies.append(policy)
    _save(policies)
    return policy

def delete_policy(policy_id):
    policies = _load()
    policies = [p for p in policies if p.get("id") != policy_id]
    _save(policies)
    return {"deleted": policy_id}

def toggle_policy(policy_id, enabled):
    policies = _load()
    for p in policies:
        if p.get("id") == policy_id:
            p["enabled"] = enabled
            break
    _save(policies)
    return {"id": policy_id, "enabled": enabled}

def get_defaults():
    return {
        "blocked_extensions": SYSTEM_BLOCKED_EXT,
        "allowed_extensions": SYSTEM_ALLOWED_EXT,
        "blocked_mime_types": SYSTEM_BLOCKED_MIME,
    }

def sync_to_postfix():
    """Regenerate Postfix checks and reload."""
    policies = _load()
    enabled = [p for p in policies if p.get("enabled", True)]

    # Build MIME header checks
    mime_rules = ["# Auto-generated by CMP - DO NOT EDIT MANUALLY"]
    # System blocked MIME types
    for mime in SYSTEM_BLOCKED_MIME:
        mime_rules.append(f"/^Content-Type:\\s*{re.escape(mime)}/i  REJECT Attachment type not allowed: {mime}")
    # Custom blocked MIME
    for p in enabled:
        if p.get("type") == "mime" and p.get("list_type") == "blacklist":
            mime_rules.append(f"/^Content-Type:\\s*{re.escape(p['value'])}/i  REJECT Attachment not allowed: {p['value']}")

    with open(MIME_CHECKS, "w") as f:
        f.write("\n".join(mime_rules) + "\n")

    # Build body checks (filename pattern)
    body_rules = ["# Auto-generated by CMP - DO NOT EDIT MANUALLY"]
    # System blocked extensions
    all_blocked_ext = list(SYSTEM_BLOCKED_EXT)
    for p in enabled:
        if p.get("type") == "extension" and p.get("list_type") == "blacklist":
            ext = p["value"].lstrip(".")
            if ext not in all_blocked_ext:
                all_blocked_ext.append(ext)

    if all_blocked_ext:
        ext_pattern = "|".join(re.escape(e) for e in all_blocked_ext)
        body_rules.append(f"/filename.*\\.({ext_pattern})$/i  REJECT Attachment type not allowed")
        body_rules.append(f"/name.*\\.({ext_pattern})$/i  REJECT Attachment type not allowed")
        # Double extension
        body_rules.append(f"/\\.({ext_pattern})\\.[a-z]{{2,4}}$/i  REJECT Suspicious double extension")

    with open(BODY_CHECKS, "w") as f:
        f.write("\n".join(body_rules) + "\n")

    # Rspamd scores
    rspamd_lines = ["# Auto-generated by CMP"]
    rspamd_lines.append("file_extensions {")
    for ext in all_blocked_ext:
        rspamd_lines.append(f'    {ext} = 6.0;')
    rspamd_lines.append("}")
    with open(RSPAMD_MIME, "w") as f:
        f.write("\n".join(rspamd_lines) + "\n")

    # Reload services
    subprocess.run(["postmap", MIME_CHECKS], capture_output=True)
    subprocess.run(["postmap", BODY_CHECKS], capture_output=True)
    subprocess.run(["postfix", "reload"], capture_output=True)
    subprocess.run(["systemctl", "reload", "rspamd"], capture_output=True)

    return {
        "synced": True,
        "blocked_extensions": all_blocked_ext,
        "mime_rules": len([r for r in mime_rules if not r.startswith("#")]),
        "body_rules": len([r for r in body_rules if not r.startswith("#")]),
    }
