"""Rspamd per-domain settings sync (spam reject thresholds)."""
import os
import subprocess

SETTINGS_PATH = "/etc/rspamd/local.d/settings.conf"


async def sync_rspamd_settings() -> dict:
    """Regenerate rspamd settings.conf from domains.spam_threshold and reload rspamd."""
    from cmp.policy.domain_policy_store import _conn
    conn = await _conn()
    try:
        rows = await conn.fetch(
            "SELECT domain_name, spam_threshold FROM domains WHERE is_active=TRUE AND spam_threshold IS NOT NULL"
        )
    finally:
        await conn.close()

    lines = ["# Auto-generated by CMP - DO NOT EDIT MANUALLY\n"]
    if rows:
        lines.append("settings {\n")
        for r in rows:
            dom = r["domain_name"]
            sid = "dom_" + "".join(ch if ch.isalnum() else "_" for ch in dom)
            thr = float(r["spam_threshold"])
            lines.append(
                f"  {sid} {{\n"
                f'    rcpt = "@{dom}";\n'
                f"    apply {{\n"
                f"      actions {{\n"
                f"        reject = {thr};\n"
                f"      }}\n"
                f"    }}\n"
                f"  }}\n"
            )
        lines.append("}\n")

    tmp = SETTINGS_PATH + ".tmp"
    with open(tmp, "w") as f:
        f.write("".join(lines))
    os.replace(tmp, SETTINGS_PATH)

    test = subprocess.run(["rspamadm", "configtest"], capture_output=True, text=True)
    if test.returncode != 0:
        raise RuntimeError("rspamd configtest failed: " + (test.stderr or test.stdout)[-300:])
    subprocess.run(["systemctl", "reload", "rspamd"], capture_output=True)
    return {"domains": len(rows)}
